update ACF example
ffraenz/private-composer-installer pull request #42
Opened 2021-10-18 14:34 UTC by macbookandrew

As currently documented with version `1.2.3`, the command `composer require "advanced-custom-fields/advanced-custom-fields-pro:*"` fails.

This brings the version up to something close to current so it doesn’t immediately fail and discourage use of this package.

An alternative might be to use a placeholder instead of `1.2.3` so it’s a bit more obvious that the user needs to set it to a current version.

2021-10-18 14:58 UTC, szepeviktor commented
Oh nooooooooooooooooooooooooooo, @macbookandrew!

![kép](https://user-images.githubusercontent.com/952007/137756591-813ad42c-92b4-451d-bce6-363de225315b.png)

That code snippet is in the **Examples** section of the README.

2021-10-18 15:01 UTC, szepeviktor commented
I know - I know...
_Copypaste_ guys are in trouble 😢

2021-10-18 15:02 UTC, macbookandrew commented
What do you think of this to make it more immediately obvious?

```diff
-    "version": "1.2.3",
+    "version": "{enter a specific version number}",
```

2021-10-18 15:04 UTC, szepeviktor commented
I think copypasting before acquiring knowledge is something I no not dare to comment!

2021-10-18 15:07 UTC, szepeviktor commented
On one hand supporting copypasters makes web development an even worse profession.
On the other hand giving a valid version makes the package more popular.

# 💣

2021-10-18 15:12 UTC, macbookandrew commented
I sympathize with the dilemma. Maybe something like this would be better to encourage people to read more closely?

```diff
-    "version": "1.2.3",
+    "version": "1.2.3", # Note: you must replace this version number
```

The example _looks_ like a valid copy/pasteable snippet and when it fails throwing a `Composer\Download\TransportException`, it’s not apparent that it’s the user’s fault for blindly copy/pasting, possibly leading users to falsely assume this package is at fault.

Whatever you think; it’s your package 🙂 

Thanks for your work on it!

2021-10-18 15:15 UTC, szepeviktor commented
> a valid copy/pasteable snippet

Actually the way you upgrade ACF is to edit `composer.json`, so when installing ACF the first time you should set the most recent version from ACF's changelog.

> it’s your package 🙂

It's @ffraenz's.

2021-10-18 15:20 UTC, macbookandrew commented
Well then…it’s up to @ffraenz and I thank him for his work on it 🙂 

I’m just hoping to help those not as experienced as you or I so they _can_ learn something rather than assuming this is broken. Have a nice day 👋🏻

2021-10-18 15:38 UTC, szepeviktor commented
> to help those not as experienced

Please consider adding a new section instead.

## Upgrade

This is how you upgrade a package installed by `private-composer-installer` ...

1. manual/scripted watch of new releases
2. update version constrain as needed
3. update version in package definition

2021-10-18 15:43 UTC, macbookandrew commented
Yeah, that would be helpful too

2021-10-19 08:18 UTC, ffraenz commented
Hi @macbookandrew, thank you for opening an issue on this. I see why the examples section might cause confusion or even frustration. I don't want to mention a specific ACF version in the README as we would need to keep it updated afterwards. Introducing a new placeholder format like `{placeholder}` could be confusing, too, as people could mistake it with the placeholders used in the dist URL. As comments are not allowed in JSON I would suggest to replace `1.2.3` by something like `REPLACE_BY_LATEST_ACF_VERSION`. For consistency let us also change the version in the 'Arbitrary private package' section.

@szepeviktor Maybe we could add an FAQ section to the README to include questions like 'How to update a package?'. We could also discuss this in a separate issue or pull request.

2021-10-19 14:21 UTC, macbookandrew commented
> I don't want to mention a specific ACF version in the README as we would need to keep it updated afterwards.

That makes total sense.

I updated the PR with your requested changes. Thanks!

2021-10-20 08:33 UTC, ffraenz requested changes
Just a small adjustment and we're good to go on this one 👍

2021-10-20 08:33 UTC, ffraenz commented on README.md
> +    "version": "REPLACE_WITH_LATEST_PLUGIN_VERSION",
Let's change this to `REPLACE_WITH_LATEST_PACKAGE_VERSION` as it may not be a plugin.

2021-10-20 08:37 UTC, szepeviktor requested changes

2021-10-20 08:37 UTC, szepeviktor commented on README.md
> +    "version": "REPLACE_WITH_LATEST_PLUGIN_VERSION",
Do we really need underscores? Resembles the DOS era :)

2021-10-20 08:40 UTC, ffraenz commented on README.md
> +    "version": "REPLACE_WITH_LATEST_PLUGIN_VERSION",
In my opinion it should be very clear that one single value is expected. That's why I'd go with the DOS style uppercase placeholder with underscores. Also I like the retro vibes ;)

2021-10-20 08:44 UTC, szepeviktor commented on README.md
> +    "version": "REPLACE_WITH_LATEST_PLUGIN_VERSION",
I see. This smells like sub-kindergarten.

![kép](https://user-images.githubusercontent.com/952007/138059749-0c547c97-674b-42f0-a8a2-9307d7c854e0.png)

2021-10-20 13:05 UTC, macbookandrew commented on README.md
> +    "version": "REPLACE_WITH_LATEST_PLUGIN_VERSION",
> Let's change this to REPLACE_WITH_LATEST_PACKAGE_VERSION as it may not be a plugin.

Of course!

2021-10-20 13:53 UTC, ffraenz approved these changes

2021-10-20 13:58 UTC, merged

2021-10-20 14:01 UTC, ffraenz commented
@macbookandrew Thanks again!

I will have a look at the failing tests in a later session. As we only updated README, it is not related to this PR.

2021-10-28 23:22 UTC, macbookandrew commented
@ffraenz  any chance you could add `hacktoberfest-accepted` label to this?

2021-10-29 08:10 UTC, ffraenz commented
Yeah, sure :)